(()=>{"use strict";const $=id=>document.getElementById(id),screens=["homeScreen","partsScreen","setupScreen","quizScreen","resultScreen","historyScreen"],letters=["A","B","C","D"],KEY="goc-theoretical-exam-history-v1";let exam="",partIndex=0,mode="test",quiz=[],index=0,score=0,answered=false,lastResult=null,deferred=null;
const show=id=>{screens.forEach(s=>$(s).classList.toggle("active",s===id));window.scrollTo({top:0,behavior:"smooth"})};
const shuffle=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const parts=()=>exam==="C1"?(window.COMPETENCE1_PARTS||[]):(window.COMPETENCE2_PARTS||[]);
const name=e=>e==="C1"?"Competence 1":"Competence 2";
function openParts(e){exam=e;const ps=parts();$("partsBadge").textContent=name(e).toUpperCase();$("partsTitle").textContent=`${name(e)} — Select Part`;$("partsSubtitle").textContent=`Choose one of ${ps.length} parts to begin.`;const g=$("partGrid");g.innerHTML="";ps.forEach((p,i)=>{const b=document.createElement("button");b.className="part-btn";b.type="button";b.innerHTML=`<strong>Part ${i+1}</strong><small>${p.length} questions</small><span>Open Part →</span>`;b.onclick=()=>openSetup(i);g.appendChild(b)});show("partsScreen")}
function openSetup(i){partIndex=i;const d=parts()[i]||[];$("setupBadge").textContent=name(exam).toUpperCase();$("setupTitle").textContent=`Part ${i+1}`;$("setupSubtitle").textContent=`${d.length} questions in ${name(exam)}, Part ${i+1}.`;[...$("countSelect").options].forEach(o=>o.disabled=o.value!=="all"&&Number(o.value)>d.length);show("setupScreen")}
function start(){const d=parts()[partIndex]||[];if(!d.length)return alert("This part did not load. Please refresh the page.");mode=$("modeSelect").value;const n=$("countSelect").value,picked=n==="all"?shuffle(d):shuffle(d).slice(0,Math.min(+n,d.length));quiz=picked.map(q=>({id:q.id,question:q.question,choices:shuffle(q.choices.map(c=>({...c})))}));index=0;score=0;answered=false;show("quizScreen");render()}
function render(){const q=quiz[index];answered=false;$("progressText").textContent=`Question ${index+1} of ${quiz.length}`;$("scoreLive").textContent=mode==="practice"?`${Math.round(score/index*100)||0}%`:"";$("progressBar").style.width=`${index/quiz.length*100}%`;$("examLabel").textContent=name(exam);$("partLabel").textContent=`Part ${partIndex+1}`;$("sourceNumber").textContent=`Source #${q.id}`;$("questionText").textContent=q.question;$("feedback").className="feedback hidden";$("feedback").textContent="";$("nextBtn").disabled=true;$("nextBtn").textContent=index===quiz.length-1?"Finish Test ✓":"Next Question →";const box=$("choices");box.innerHTML="";q.choices.forEach((c,i)=>{const b=document.createElement("button");b.type="button";b.className="choice";b.innerHTML=`<span class="letter">${letters[i]}</span><span class="choice-text"></span>`;b.querySelector(".choice-text").textContent=c.text;b.onclick=()=>choose(i);box.appendChild(b)})}
function choose(i){if(answered)return;answered=true;const q=quiz[index],bs=[...$("choices").children],c=q.choices[i];bs[i].classList.add("selected");if(c.correct){score++;bs[i].classList.add("correct");$("feedback").className="feedback good";$("feedback").textContent=mode==="practice"?"✓ Correct answer.":"Answer recorded."}else{bs[i].classList.add("wrong");const ci=q.choices.findIndex(x=>x.correct);if(mode==="practice"&&ci>=0){bs[ci].classList.add("reveal");$("feedback").className="feedback bad";$("feedback").textContent=`✗ Incorrect. Correct answer: ${letters[ci]}.`}else{$("feedback").className="feedback";$("feedback").textContent="Answer recorded."}}$("nextBtn").disabled=false}
function next(){if(!answered)return;if(index<quiz.length-1){index++;render()}else finish()}
function finish(){const pct=Math.round(score/quiz.length*100);lastResult={exam,part:partIndex+1,score,total:quiz.length,percent:pct,mode,date:new Date().toISOString()};const h=history();h.unshift(lastResult);localStorage.setItem(KEY,JSON.stringify(h.slice(0,100)));$("resultScore").textContent=`${pct}%`;$("resultDetails").textContent=`${name(exam)}, Part ${partIndex+1}: ${score} correct out of ${quiz.length}.`;$("resultTitle").textContent=pct>=80?"Excellent Work!":pct>=60?"Good Work":"Keep Practicing";$("resultIcon").textContent=pct>=80?"🏆":pct>=60?"⚓":"📚";show("resultScreen")}
function history(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}
function renderHistory(){const list=$("historyList"),h=history();list.innerHTML="";if(!h.length){list.innerHTML=`<div class="info-card">No tests completed yet.</div>`;return}h.forEach(r=>{const e=document.createElement("div");e.className="history-item";e.innerHTML=`<div><strong>${name(r.exam)} • Part ${r.part} • ${r.mode==="practice"?"Practice":"Test"}</strong><small>${new Date(r.date).toLocaleString()} • ${r.score}/${r.total}</small></div><div class="history-score">${r.percent}%</div>`;list.appendChild(e)})}
function home(){show("homeScreen")}function quit(){if(confirm("Quit this test? The current attempt will not be saved."))home()}
document.querySelectorAll(".exam-card").forEach(b=>b.onclick=()=>openParts(b.dataset.exam));$("homeTopBtn").onclick=home;$("partsBackBtn").onclick=home;$("setupBackBtn").onclick=()=>openParts(exam);$("beginBtn").onclick=start;$("nextBtn").onclick=next;$("quitBtn").onclick=quit;$("historyBtn").onclick=()=>{renderHistory();show("historyScreen")};$("historyBackBtn").onclick=home;$("clearHistoryBtn").onclick=()=>{if(confirm("Clear all saved history?")){localStorage.removeItem(KEY);renderHistory()}};$("retryBtn").onclick=()=>openSetup(partIndex);$("resultPartsBtn").onclick=()=>openParts(exam);$("resultHomeBtn").onclick=home;
addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("installBtn").classList.remove("hidden")});$("installBtn").onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;$("installBtn").classList.add("hidden")};if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.warn))})();